# Generated by Django 3.0.3 on 2020-02-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=32)),
                ('price', models.FloatField()),
                ('image', models.ImageField(default=None, upload_to='')),
                ('description', models.TextField(default=None)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(db_index=True, default=None, max_length=128)),
                ('number', models.IntegerField(default=None)),
                ('user', models.CharField(max_length=150)),
                ('full_price', models.FloatField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
