# Generated by Django 3.0.3 on 2020-02-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=32)),
                ('price', models.FloatField()),
                ('image', models.ImageField(default=None, upload_to='')),
                ('description', models.TextField(default=None)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
