# Generated by Django 3.0.3 on 2020-02-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(default='https://st2.depositphotos.com/1000244/8482/v/950/depositphotos_84820530-stock-illustration-pizza-question-symbol.jpg'),
        ),
    ]
